### ISSUE TITLE
PB Appears if unused

### ISSUE THREAD

**Issue by jinhofer** [deraadt/Moodle-block_progress#10]
Michael,

We have noticed that if there are no courses currently using the Progress Bar but the Progress Bar block is being utilized on /my, it appears as shown:
![image](https://cloud.githubusercontent.com/assets/8837519/6687551/df695cec-cc79-11e4-8b18-61b3b15a8935.png)
Would it be possible to have the Progress Bar display only if there is at least one course using the Progress Bar block?

**Comment by deraadt** [comment]
Hi, Joe.

Thanks for reporting this.

I'll handle this on the Tracker...

https://tracker.moodle.org/browse/CONTRIB-5637
