### ISSUE TITLE
Clash with mod_bigbluebutton

### ISSUE THREAD

**Issue by glydetech** [deraadt/Moodle-block_progress#15]
Moodle version: 2.9.2+ (Build: 20150924)
mod_bigbluebutton version: 2015080603
block_progress version: 2015091800

When trying to use the 'select activities/resources' button, the error 'error reading from database' is displayed with this error in the logs:

```
2015/10/02 10:27:02 [error] 8549#0: *39086 FastCGI sent in stderr: "PHP message: Default exception handler: Error reading from database Debug: Unknown column 'timedue' in 'field list'
SELECT id, name, timedue as due FROM mdl_bigbluebuttonbn WHERE course='61' ORDER BY name
[array (
)]
Error code: dmlreadexception
* line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 1080 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 142 of /blocks/progress/edit_form.php: call to mysqli_native_moodle_database->get_records_sql()
* line 64 of /blocks/edit_form.php: call to block_progress_edit_form->specific_definition()
* line 195 of /lib/formslib.php: call to block_edit_form->definition()
* line 57 of /blocks/edit_form.php: call to moodleform->moodleform()
* line 1353 of /lib/blocklib.php: call to block_edit_form->__construct()
* line 1149 of /lib/blocklib.php: call to block_manager->process_url_edit()
* line 1457 of /lib/pagelib.php: call to block_manager->process_url_actions()
* line 888 of /lib/pagelib.php: call to moodle" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /training/course/view.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "moodle.dkit.ie", referrer: "https://moodle.dkit.ie/training/course/view.php?id=61"
```

It seem, that since version 2 of the big blue button module, the database field 'timedue' no longer exists. There are two other database fields 'openingtime' and 'closingtime'.

As a workaround, commenting out line 160 in blocks/progress/lib.php works:

```
        'bigbluebuttonbn' => array(
//            'defaultTime' => 'timedue',
            'actions' => array(
```

**Comment by sorted2323** [comment]
THANK YOU!!!! This was driving me insane, I even restored a database backup and and uninstalled bigblue button and was STILL having this issue. Does this allow big blue button to function properly?? I'm scared to re-install now!

**Comment by sorted2323** [comment]
By the way this was happening on Moodle 2.6 as well

**Comment by deraadt** [comment]
Thanks for reporting this, Andrew.

I've created the following issue to implement a change and your input is welcome there.

https://tracker.moodle.org/browse/CONTRIB-5979

**Comment by deraadt** [comment]
Commenting here to say that I've resolved the issue above.
