### ISSUE TITLE
problems with multilang on /my/ area

### ISSUE THREAD

**Issue by antton** [deraadt/Moodle-block_progress#16]
Hi, I just try to add a progress bar that i'm using on a course into my own area, the title of the block is working with the following multilang.

<span class="multilang" lang="es">UD1: PROGRESO</span><span class="multilang" lang="eu">UD1: PROGRESIOA</span><span class="multilang" lang="en">UD1: PROGRESS</span>

The course progress bar block is rendering properly the multilang but now as I said in the /my/ area.

Thanks

**Comment by antton** [comment]
The solution is to change the line 179 from block_progress.php

                            $this->content->text .= HTML_WRITER::tag('p', s($blockinstance->config->progressTitle));

with this one

                            $this->content->text .= HTML_WRITER::tag('p', s(format_string($blockinstance->config->progressTitle)));

Thant's all ;)

**Comment by deraadt** [comment]
I've resolved this in https://tracker.moodle.org/browse/CONTRIB-5956
