### ISSUE TITLE
Display of 'Inactive' students - should only display 'Active' students.

### ISSUE THREAD

**Issue by ActionJONA** [deraadt/Moodle-block_progress#17]
Hi, 

The Progress bar doesn't take into account whether the students are active or not in a course - therefore when viewing the overview of students, it shows all students, including the inactive ones not needed.

(We use self enrolment for courses - meaning that when the student's enrolment ends, they become inactive).

**Comment by deraadt** [comment]
Hi.

Thanks for reporing this. I'll handle this in the Moodle Tracker...

https://tracker.moodle.org/browse/CONTRIB-5993
