### ISSUE TITLE
Firefox too slow rendering configuration page (and possible "solution")

### ISSUE THREAD

**Issue by antton** [deraadt/Moodle-block_progress#18]
Hi, the progress bar block configuration page is too slow rendering with firefox when you have a lot of activities. I was thinking looking at the code that it would be quite easy to introduce a pagination system, just letting firefox render by modules or topics. What do you think about it? I read more people asking about the slow rendering of firefox, and that's why I'm trying to find out a "good" solution.

I will let you know if I get it done.

Thanks

**Comment by antton** [comment]
I just find a better solution at least for us, by default I let all the topics collapsed just removing the following lines on edit_form.php

if (method_exists($mform, 'setExpanded')) {
                        $mform->setExpanded('section'.$i);

Now it's really fast opening the edit page. It would be nice to put a global variable on the progress bar settings and check if we want open or not by default.

**Comment by deraadt** [comment]
Hi, Antton.

Could we please continue this conversation on the following Moodle Tracker issue?

https://tracker.moodle.org/browse/CONTRIB-5958

I am intrigued by your finding about hiding sections.
