### ISSUE TITLE
Issues with filtering in the "Overview of students" view

### ISSUE THREAD

**Issue by johnnypraxis** [deraadt/Moodle-block_progress#29]
To reproduce the issues
1) Click the "Overview of students" button in the progressbar block
2) Click on the "Visible groups" dropdown and select a group with many students. You need to select a group with enough students to be able to click "Page 2" in the pagination.
3) Click on the "Page 2" link in the pagination

We wanted to display page 2 but page 2 is not displayed. Instead the filtering group dropdown selection is cleared and all the students in all the groups are displayed.

4) Furthermore the sort order in the list is descending the first time a column name is clicked to sort. The default list-ordering in Moodle is ascending. This is an issue as well in the "Overview of students" view.

See the issues in this screenshot:
http://screencast.com/t/JjLSN3Ds6z

Moodle version is 2.9.4. Progress bar block version is 2016031101.

**Comment by deraadt** [comment]
Yep, that looks like a bug.

It will have to do with how the new grouping selector I recently created and the paging are working together. Hopefully I'll have a chance to look at this soon.

PS. I prefer to issues to be reported on the Moodle Tracker.

**Comment by deraadt** [comment]
Thanks for posting this on the Moodle Tracker. I'll handle it there.
