### ISSUE TITLE
How about "losing" the "now" indicator, and use some other visual indicator?

### ISSUE THREAD

**Issue by nadavkav** [deraadt/Moodle-block_progress#32]
Maybe have a bold border around the current activity, like:
![image](https://cloud.githubusercontent.com/assets/231168/14520912/8384f318-022f-11e6-87da-54a27f1219fd.png)

As I am looking (was asked by teachers) for a more clear/simple UI
What do you think, does it make any sense?

**Comment by deraadt** [comment]
I see the potential. With the new presentation option that includes wrapping, there is not a good way to show the NOW indicator there. But I don't think it will work as there is no "current" activity, there is only activities with expected dates in the past and others with dates in the future.

**Comment by nadavkav** [comment]
You are right. so, maybe have that border indicator only replace the NOW label?

**Comment by nadavkav** [comment]
Btw, we added a new blocks region above the content of the "course" & "incourse" layouts.
and placed the progressbar in that region. see attached screen capture:
![image](https://cloud.githubusercontent.com/assets/231168/14552367/5fb3141c-02e6-11e6-9d07-092ca5868415.png)

**Comment by deraadt** [comment]
That looks great. How difficult was it to add that area there?

I reckon it would be good if there could be a module that simulated a block in the main course section. If we do away with blocks in future, that could help with the transition.

**Comment by nadavkav** [comment]
It was just two lines of code. one on the relevant page layout (columns3.php) and another on the config.php (adding the block region name to the list)

I agree the a module that simulate blocks could be great! I will check it out and see how easy it can be...

**Comment by deraadt** [comment]
Could you please share the changes you made? People have asked for this 
and I'd like to share it on the docs page.

Photo of Michael de Raadt 	Michael de Raadt /PhD/
/Research Director/
michaeld@moodle.com <mailto:michaeld@moodle.com>
@salvetore <https://twitter.com/salvetore> @moodleresearch 
<https://twitter.com/moodleresearch>
	<http://moodle.com/hq/>
The world's open source learning platform

**Comment by nadavkav** [comment]
Here goes...
go into your-theme/config.php and update the "incourse" layout with a new blocks region named "above-content" like so:
```
'incourse' => array(
        'file' => 'columns3.php',
        'regions' => array('side-pre', 'side-post', 'above-content'),
        'defaultregion' => 'side-pre',
    ),
```
Then, go into your-theme/layout/column3.php and add the following line of code:
```
  <?php echo $OUTPUT->blocks('above-content', 'span12'); ?>
```
so it looks like:
```
<section id="region-main" class="span8 pull-right">
  <?php echo $OUTPUT->blocks('above-content', 'span12'); ?>
  <?php
       echo $OUTPUT->course_content_header();
       echo $OUTPUT->main_content();
```
To your English lang file you should add something like:
```
$string['region-above-content'] = 'Above content';
```
I am using the Elegance theme, that is based over theme/bootstrap (and not bootstrapbase). but it is all the same for any theme you choose.

**Comment by nadavkav** [comment]
I almost think this should go into core, for Clean and More themes, as it will expand the possibilities of course content presentation.
