### ISSUE TITLE
add functionality (automatically send a message alert)

### ISSUE THREAD

**Issue by ivakh** [deraadt/Moodle-block_progress#35]
Dear, you can add a functionality ?, the idea is that the progress bar can detect students who have not completed an activity and automatically send a message alert to one or more course participants, so will be able to help each other and it is a way to encourage collaborative work, thanks for you time!!! and congratulation this is a excellent block!

**Comment by deraadt** [comment]
You might want to watch and contribute to the following issue...

https://tracker.moodle.org/browse/CONTRIB-5689
